export const KEYS = {
    "en" : {
        "lines" : {
            "0" : { "Backquote" : ["`", "~"],
                        "Digit1" : ["1", "!"],
                        "Digit2" : ["2", "@"],
                        "Digit3" : ["3", "#"],
                        "Digit4" : ["4", "$"],
                        "Digit5" : ["5", "%"],
                        "Digit6" : ["6", "^"],
                        "Digit7" : ["7", "&"],
                        "Digit8" : ["8", "*"],
                        "Digit9" : ["9", "("],
                        "Digit0" : ["0", ")"],
                        "Minus" : ["-", "_"],
                        "Equal" : ["=", "+"],
                        "Backspace" : "backspace"},
            "1" : { "Tab" : "tab",
                        "keyQ" : ["q", "Q"],
                        "keyW" : ["w", "W"],
                        "keyE" : ["e", "E"],
                        "keyR" : ["r", "R"],
                        "keyT" : ["t", "T"],
                        "keyY" : ["y", "Y"],
                        "keyU" : ["u", "U"],
                        "keyI" : ["i", "I"],
                        "keyO" : ["o", "O"],
                        "keyP" : ["p", "P"],
                        "BracketLeft" : ["[", "{"],
                        "BracketRight" : ["]","}"],
                        "Backslash" : ["backslash", "|"]},
            "2" : { "CapsLock" : "caps lock",
                        "KeyA" : ["a", "A"],
                        "KeyS" : ["s", "S"],
                        "KeyD" : ["d", "D"],
                        "KeyF" : ["f", "F"],
                        "KeyG" : ["g", "G"],
                        "KeyH" : ["h", "H"],
                        "KeyJ" : ["j", "J"],
                        "KeyK" : ["k", "K"],
                        "KeyL" : ["l", "L"],
                        "Semicolon" : [";", ":"],
                        "Quote" : ["apostrophe", "quote"]},
            "3" : { "ShiftLeft" : "shift",
                        "KeyZ" : ["z", "Z"],
                        "KeyX" : ["x", "X"],
                        "KeyC" : ["c", "C"],
                        "KeyV" : ["v", "V"],
                        "KeyB" : ["b", "B"],
                        "KeyN" : ["n", "N"],
                        "KeyM" : ["m", "M"],
                        "Comma" : [",", "<"],
                        "Period" : [".", ">"],
                        "Slash" : ["/", "?"]},
            "4" : { "Keyboard" : "kb_hide",
                        "Space" : "space",
                        "ArrowLeft" : "arrowleft",
                        "ArrowRight" : "arrowright"}
            },
        "letters" : "qwertyuiopasdfghjklzxcvbnm"
    },
    "icons" : {
        "volume_on" : "icon icon-always",
        "volume_off" : "icon icon-always",
        "tab" : "icon",
        "kb_hide" : "icon icon-always",
        "caps lock" : "icon",
        "mic" : "icon icon-always",
        "enter" : "icon",
        "space" : "icon",
        "backspace" : "icon",
        "shift" : "icon",
        "ins" : "icon",
        "del" : "icon",
        "alt" : "icon"
            },
    "specials" : {
        "backslash" : "&bsol;",
        "apostrophe" : "&apos;",
        "quote" : "&quot;",
        "arrowup" : "&uarr;",
        "arrowleft" : "&larr;",
        "arrowdown" : "&darr;",
        "arrowright" : "&rarr;"
    },
    "replaces" : {
        "enter" : 13,
        "space" : 32,
        "tab" : 9,
        "apostrophe" : 39,
        "quote" : 34,
        "backslash" : 92
    }
}

